version: '2'
services:
  web:
    image: socketwench/dropwhale-web
    ports:
      - "80:80"
    volumes_from:
      - php
    depends_on:
      - php
    env_file:
      - dropwhale.settings
  php:
    image: socketwench/dropwhale-php
    volumes:
      - .:/module
      # - ./.dropwhale/data/drupal:/tmp/drupal
    env_file:
      - dropwhale.settings
  db:
    image: socketwench/dropwhale-db
    ports:
      - 3306:3306
    env_file:
      - dropwhale.settings
