web:
   build: web
   ports:
      - "80:80"
   volumes_from:
      - data
   links:
      - db
db:
   build: db
   ports:
      - 3306:3306
   environment:
      - MYSQL_DB=drupal8
      - MYSQL_USER=drupal
      - MYSQL_PASS=thisisawesome
cli:
   build: cli
   volumes_from:
      - data
   links:
      - db
      - web
data:
   image: tianon/true
   volumes:
         - /var/www
         - ..:/var/www/modules/flag