version: '2'
services:
  web:
    build: web
    ports:
      - "80:80"
    volumes_from:
      - php
    depends_on:
      - php
  php:
    build: php
    volumes:
       - ./data/drupal:/var/www/html
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
  db:
     build: db
     ports:
      - 3306:3306
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=drupal
       - MYSQL_USER=drupal
       - MYSQL_PASSWORD=drupal
